### ISSUE TITLE
Support Different OS File Separators 

### ISSUE THREAD

**Issue by zachsez** [kyclark/tiny_python_projects#11]
Use the `os.sep` constant instead of hard coded `/` to support Windows execution.  
**From:** `prg = ./hello.py`
**To:** `prg = '.' + os.sep + 'hello.py'`

[Example of Issue](https://github.com/kyclark/tiny_python_projects/blob/f9151ba80c78301b62c724d9ed9c2a0c493c021a/01_hello/test.py#L7)

[OS Docs](https://docs.python.org/3/library/os.html)

**Comment by kyclark** [comment]
Great point. Really WSL is required to effectively use the material. I've tried to use a Windows command line, and it's just nearly impossible to get things to work correctly, e.g., the shebang. I hate having to prefix my commands with "python" (or "python.exe" or "python3" or whatever). I strongly encourage Windows users to install WSL and perhaps use VS Code (you can type "code prg.py" on the command line to open the editor with that program!).
