### ISSUE TITLE
itictactoe No winner if win at the last turn

### ISSUE THREAD

**Issue by ceilinglight** [kyclark/tiny_python_projects#16]
Hi,

In chapter 22 Tic-Tac-Toe redux: An interactive version with type hints, the solution doesn't declare a winner if they win at the last turn. Here's the output from ```tiny_python_projects/22_itictactoe/solution1.py```
```
-------------
| X | O | O |
-------------
| X | O | X |
-------------
| 7 | X | O |
-------------
Player X, what is your move? [q to quit]: 7
All right, we'll call it a draw.
```
The program should check for a draw after displaying a new board and finding a winner.

**Comment by kyclark** [comment]
You're right! I should do all the checks before getting the next move.
