### ISSUE TITLE
Issue with command line arguments example

### ISSUE THREAD

**Issue by k3sh4vk** [kyclark/tiny_python_projects#20]
Hi. I love this book and have started the journey a few days before. I do not know whether this is an issue or just the way python/argparse handles the situation below

`#!/bin/env python3`
`#Purpose: Say hello`

`import argparse`

`parser = argparse.ArgumentParser(description='Say hello')`
`parser.add_argument('-n','--name',metavar='name',default='World',help='Name to greet')`
`args = parser.parse_args()`
`print('Hello, ' + args.name + '!')`

This code when executed gives proper output as per the book like

`./hello.py -n Keshav`
OUTPUT
`Hello, Keshav!`

`./hello.py --name Keshav`
OUTPUT
`Hello, Keshav!`

However, correct output is also given if code is executed the following way :-

`./hello.py --n Keshav`
OUTPUT
`Hello, Keshav!`

`./hello.py --na Keshav`
OUTPUT
`Hello, Keshav!`

`./hello.py --nam Keshav`
OUTPUT
`Hello, Keshav!`

Please suggest and explain if possible what is happening. Thank you so much. :-)

**Comment by JAIDHEER007** [comment]
Set ```allow_abbrev``` as ```False``` in  ```ArgumentParser()``` method. 

```
from argparse import ArgumentParser
import sys

parser = ArgumentParser(description='Say hello', allow_abbrev=False)

parser.add_argument('--name', '-n',metavar='str', help='The name to greet (default: World)', type=str, default='World')

# print(sys.argv)

args = parser.parse_args(sys.argv[1:])
print('Hello, {}!'.format(args.name))
```

### Output:
```python hello.py```
```Hello, World!```

```python hello.py --name Jaidheer```
```Hello, Jaidheer!```

```python hello.py -n Jaidheer```
```Hello, Jaidheer!```

```python hello.py --na Jaidheer```
```
usage: hello.py [-h] [--name str]
hello.py: error: unrecognized arguments: --na Jaidheer
```

```python hello.py --nam Jaidheer```
```
usage: hello.py [-h] [--name str]
hello.py: error: unrecognized arguments: --na Jaidheer
```
---
```allow_abbrev``` was introduced in python 3.5, so check  for compatibility. 

If a wrong command line argument is passed the program will terminate abruptly. 

## Useful Links
* [about argparse](https://docs.python.org/3/library/argparse.html)
* [about allow_abbrev](https://docs.python.org/3/library/argparse.html#allow-abbrev)
* [about exit_on_error](https://docs.python.org/3/library/argparse.html#exit-on-error)

**Comment by kyclark** [comment]
I did not know about disallowing abbreviations. That is really useful! Thanks.
