### ISSUE TITLE
The term 'python3' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by numantyke** [kyclark/tiny_python_projects#40]
I am running python 3.11.0 and when I run "pytest -xv test.py" I get this red error under the "test_runnable" FAILURES: 
E       assert "'python3' is...r batch file." == 'Hello, World!'
E         - Hello, World!
E         + 'python3' is not recognized as an internal or external command,
E         + operable program or batch file.

I try to run the command "python3 hello.py" and I get this error
python3 : The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the     
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python3 hello.py
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Any help on how I can fix this would be great.

**Comment by numantyke** [comment]
just change everywhere in the test files is "Python3" to "Python" and you are good to go.

**Comment by nbehrnd** [comment]
@numantyke In case the computer you are using runs Linux, it is first up to the authors of the distribution how the programs and packages are named in the package managers, and eventually called from the CLI.  In the case of `pytest` for example, for some time, there was *pytest for (now legacy) Python 2* which you called by `pytest my_program.py`.  All while at the same time, there equally was *pytest for (now contemporary) Python 3* which you called by `pytest-3 my_program.py`.  If you happen to work with a Linux distribution which never used Python 2 (e.g., Xubuntu 20.04 LTS fossa, or more recent), chances are that a call like  `pytest my_program.py` now (implicitly) refers to the pytest for Python 3 only.

More generally speaking, however, you may set an `alias` in your shell's configuration file.  In case you use `bash`, this would be `.bashrc` in your home directory.  If applied with care, you may (re)define how programs/combination of instructions are easier accessible to you.  E.g.,  an entry of

```
alias mv="mv -i"  # safety guard to prevent unintentional overwriting
```

in this register and restart of your bash (`source ~/.bashrc`) will prevent a file being moved accidentally overwrite an other file of same file name.  The concept is briefly described e.g., by [softwarecarpentry](https://v4.software-carpentry.org/shell/var.html).
