### ISSUE TITLE
test_excutable()  E AssertionError: asser ''=='Hello, World!' E -Hello, World!

### ISSUE THREAD

**Issue by numantyke** [kyclark/tiny_python_projects#41]
________________________________________________________________ test_executable __________________________________________________

    def test_executable():
        """Says 'Hello, World!' by default"""

        out = getoutput(prg)
>       assert out.strip() == 'Hello, World!'
E       AssertionError: assert '' == 'Hello, World!'
E         - Hello, World!

test.py:30: AssertionError

To fix this I went into the "test.py" file and changed line: 29. It works when you change it to this:
out = getoutput(f'python {prg}')

**Comment by itx-mubee** [comment]
I can do your work
follow me up on mubeenriaz2006@gmail.com
for further information

**Comment by JPL-JUNO** [comment]
after change line to `out = getoutput(f'python {prg}')`, the function will be the same with 'test_runnable()', maybe this not the correct solution

**Comment by kyclark** [comment]
The given code works on Unix-style OS (macOS, Linux). Your change is probably necessary for Windows.
